### ISSUE TITLE
[meta] redesign cell display to remove clutter

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#12]
I put together an mvp cell design to simply get all the underlying logic in-place. Ultimately getting the actual result displays looking closer to a well-formulated document (like RMarkdown) is the goal. Will update this list w/ more points as I tweak / commit.

- [x] move buttons to right of cell
- [x] tweak the CodeMirror instances for cleanup
- [x] keep buttons invisible until cell hover
