### ISSUE TITLE
[META] redo external scripts cell

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#164]
The external scripts cell needs the following:

- [x] a better way to list multiple external dependencies
- [x] way to show if an external script has successfully loaded / failed
- [x] support for external style sheets & js
