### ISSUE TITLE
[META] exporting bundles

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#194]
Post-Austin, this will be the next big feature push -- we need to build the stuff needed to deliver the vision of portability we've described.

that means
- [x] defining the “jsmd” syntax we want to use for export (just text with cell divisions rather than a JSON blob to allow use with diff tools and other text-based tools). The jsmd will also need a header/meta section with:
    - [ ] hashes of notebook jsmd for traceability, and pointer to previous version hash
    - [ ] other settings at time of export, including: bundle version, inlined js vs cdn js, etc
- [x] figuring out how to serialize complete HTML file with bundled code from within the app
- [ ] building an "advanced export" menu with extra export options; also, figuring out what the default export is, whether we want to maintain a semantic distinction between "export" (just the jsmd?) and "bundle" (a complete runnable package)
- [ ]  Export/import jsmd to gists or other external repos

**Comment by wlach** [comment]
@hamilton and I were just chatting about this. I think we should implement exporting/importing notebooks via gist. This would facilitate a workflow where people could share notebooks just via a URL, similar to how people used to do things with nbviewer before gist provided a native notebook view. For example:

http://nbviewer.jupyter.org/github/gestaltrevision/python_for_visres/blob/master/index.ipynb

**Comment by hamilton** [comment]
@wlach going to create an issue for this so we can flesh out a spec & get to it :)

**Comment by bcolloran** [comment]
colsing in favor of more detailed issues
