### ISSUE TITLE
[META] demos: come up with javascript for ____ users

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#195]
We need to have demo notebooks that mirror some of the rosetta stone type docs out there for other languages:

- [ ] javascript for R users
- [ ] javascript for NumPy users
- [ ] javascript for Matlab users
- [ ] javascript for Julia users

**Comment by bcolloran** [comment]
Issue moved to [iodide-project/iodide-examples #1](https://github.com/iodide-project/iodide-examples/issues/1) via [**ZenHub**](https://www.zenhub.com/)
