### ISSUE TITLE
[META] aim for high test coverage

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#196]
As of this filing, we've mostly focused on testing the reducers. We still need to:

- [ ] complete the reducer tests.
- [ ] decompose the reducers further, and test some of the more atomic actions
- [ ] write the appropriate tests for components - cells, header, etc.

**Comment by rvwatch** [comment]
Hello Iodide friends! I'm a first-time contributor and figured I'd knock out some reps for basic actions tests. I've created an actions.test.js file and added 31 basic tests to help get started. Would that be something you'd like me to create a PR for?

**Comment by bcolloran** [comment]
Hi @rvwatch! Yeah, a PR for that sounds great, thanks! :-)

**Comment by bcolloran** [comment]
stale; need to think more about tests, but will need more specific issues/spints
