### ISSUE TITLE
[META] presentation mode design changes

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#199]
In terms of functionality, presentation mode is mostly-implemented. In terms of readability and general aesthetics, it needs a bit of work.

- [x] The block-level element styling doesn't feel 100% right at the moment. Let's fix the spacing and follow typical design principles around these things.
- [x] Having near full-width for text and code in presentation mode makes the text fairly unreadable. This should not be the default.
- [ ] Allowing the option for a Table of Ccontents would be very useful for longer reports and presentations.
- [x] We should make sure all the correct css classes are in-place for easy theming of presentations.

**Comment by hamilton** [comment]
I'm going to close this since #483 addresses everything in-scope for this. I would say the ToC is `wontfix` for now.
