### ISSUE TITLE
[meta] mvp keybindings, pt. 1

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#2]
We need to implement jupyter-style keybindings for:

- [x] entering / exiting command mode (lifted directly from jupyter)
- [x] selecting the next / previous cell
- [x] moving a selected cell up and down
- [x] adding / inserting a cell
- [x] deleting a cell
- [x] running a cell
- [x] switching between cell types

Given that these are `Page`-specific, we can implement the keybindings in that component.
