### ISSUE TITLE
Proposal of Roadmap for Globalization of Iodide

### ISSUE THREAD

**Issue by mehmetoguzderin** [iodide-project/iodide#2033]
# Roadmap for Globalization of Iodide

| Steps | Internationalization | Localization |
| :-: | :-: | :-: |
| 0 | Proposal of Internationalization Support for Iodide System | Proposal of Metadata Support for Iodide Notebooks |
| 1 | ∅ | Proposal of Identifier Support for Iodide Notebook Cells |
| 2 | ∅ | Proposal of Selector Support for Iodide Notebook Cells |
| 3 (MVP) | ∅ | Proposal of Localization Support for Iodide Notebook Cells |
| 4 | ∅ | Proposal of Localization Files for Iodide Notebooks |

## Tracker

- [ ] **Proposal of Internationalization Support for Iodide System** Published
- [ ] Minimum Viable Product of **Proposal of Internationalization Support for Iodide System** Implemented

- [ ] **Proposal of Metadata Support for Iodide Notebooks** Published
- [ ] Minimum Viable Product of **Proposal of Metadata Support for Iodide Notebooks** Implemented

- [ ] **Proposal of Identifier Support for Iodide Notebook Cells** Published
- [ ] Minimum Viable Product of **Proposal of Identifier Support for Iodide Notebook Cells** Implemented

- [ ] **Proposal of Selector Support for Iodide Notebook Cells** Published
- [ ] Minimum Viable Product of **Proposal of Selector Support for Iodide Notebook Cells** Implemented

- [ ] **Proposal of Localization Support for Iodide Notebook Cells** Published
- [ ] Minimum Viable Product of **Proposal of Localization Support for Iodide Notebook Cells** Implemented

- [ ] **Proposal of Localization Files for Iodide Notebooks** Published
- [ ] Minimum Viable Product of **Proposal of Localization Files for Iodide Notebooks** Implemented
