### ISSUE TITLE
[META] overall styling improvements

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#210]
- [ ] have a few different themes for presentation mode: something that resembles a "dashboard" theme, something that resembles a "NYT data presentation" theme (which is perhaps a general report theme).
- [x] consider using css grids + polyfill for better cell support (#207) 
- [x] implement `CSSCell` for custom style hacking in-notebook (#189)
- [x] redesign some elements of presentation mode so that it "works" out the box the way users expect
- [ ] ~~remove saved notebooks from menu and push into an overlay (#209)~~

**Comment by bcolloran** [comment]
obselete
