### ISSUE TITLE
[META] improve jsmd metadata

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#372]
breaking out some of the unfinished parts of #194 

Improve the jsmd header/meta section with:
- [ ] hashes of notebook jsmd for traceability #370
- [ ] pointer to previous exported jsmd hash 
- [ ] notebook export number
- [x] datetime at export #371 
- [ ] iodide app version

**Comment by hamilton** [comment]
Closing this since the `direct-jsmd-editing` branch + our server component has made these features obsolete
