### ISSUE TITLE
[META] menu tune-ups

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#475]
Filing this as a single checklist issue rather than a bunch of issues to avoid clutter. I think this GIF should demonstrate all the things i'm noticing--

![peek 2018-03-11 15-29](https://user-images.githubusercontent.com/2380975/37259242-f88c7772-2540-11e8-9952-7f9149c8e920.gif)

- [x] drawing/hiding menus feel a little sluggish, but especially hiding. It's subjective of course, but to me it makes that part of the app feel slow rather than snappy.
- [ ] need to click on each submenu to display it, rather than just unfolding submenus on hover, which is the design convention for desktop UIs
- [x] when a submenu is open, clicking outside the menus only closes the submenu; should close all menus. "clicking outside the menus" refers to clicks entirely outside of the menus and any submenus; clicking at menu higher in the heirarchy should only close menus lover in the heirarchy. clicking outside **all** menus should close all menus
- [ ] when you click outside the root menu (which closes it), the "menu" tooltip is shown again and remains shown until another click, or until some (but not all) uiTask is fired (kbd up/down to select cells doesn't make the tooltip go away, but 'enter' to go into cell edit mode does make the tooltip vanish)
- [x] "cell" submenu missing "add cell above     A"
- [x] submenu text sppears to be a bit smaller than top level menu text. increase size of submenu text (it's too small)

Please note that if you want to work on any of these subissues, you don't have to have one big PR tackling all of them. In fact, little PRs taking them one step at a time can be prefereable (but if you find that all these subissues are tangled up together, larger PRs addressing several at once will be ok)

**Comment by bcolloran** [comment]
regarding the behavior in #485-- if you want to switch menu subsections -- e.g., you first click on the "notebooks" heading, which opens that submenu, but you then wish to look in the "cells" submenu, clicking the "cells" heading does not open the cells submenu, it closes all the menus. so, to specify the behavior a little more:

- [ ] when a submenu is open, clicking outside the menus only closes the submenu; should close all menus. "clicking outside the menus" refers to clicks entirely outside of the menus and any submenus; clicking at menu higher in the heirarchy should only close menus lover in the heirarchy. clicking outside **all** menus should close all menus

i updated the original item and unchecked the box so that we can track it here.

i'm going to revert that PR; the current behavior is actually a bit less desirable than the previous behavior.

**Comment by hamilton** [comment]
Sounds good - sorry for not QAing more fully.

FWIW I'm feeling very bearish on how the Material UI folks document which features aren't fully implemented yet. In their readme they have a [strong recommendation](https://github.com/mui-org/material-ui/issues/8152) to use beta yet their documentation does not suggest which features haven't been implemented in beta that HAVE been implemented in 0.20.0 (the old stable release they haven't updated in a minute). I think there are solutions to all of these issues for sure, but we don't get this stuff magically added in.

So a solution to some of these ui tweaks may require a bit of thinking, vs. just finding the feature in the docs that describes out to do this. Not that thinking ever hurt anyone.

**Comment by bcolloran** [comment]
that makes sense @hamilton. in fairness to the material-ui thing, it's focused on providing a UI that will work for touch (where desktop style nested menus are not a great pattern) and we're really making a much more traditional desktop productivity app. But luckily, thanks to React and your recent modularization of the menus, if we want to try substituting in a more traditional menu component and wrapping it in a dark theme, we can try it without too too much difficulty :-)

You know all the moving part better than I do so I defer to you -- just sayin that there wouldn't be any shame in experimenting with that approach if contorting the material-ui components to meet our needs turns out to be a pain (either because our needs are out of scope for that project or b/c their docs just aren't up to snuff).

**Comment by shkamaru** [comment]
Hi, I did made some changes to hover it but the unhover functions for material-ui are not working and I am stuck in it. So, any other approach for fixing the unhover issue?

**Comment by hamilton** [comment]
We've removed submenus from the client, so I'm closing this.
