### ISSUE TITLE
[META] "pinned cells" side pane

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#521]
Large notebooks are difficult to navigate. Sometimes, for example, a helper function defined in a cell toward the top of a notebook needs one small edit so that a cell much farther down the notebook can support another argument. Right now I have to scroll to find the cell Another example: CSS cells end up having to be made near the code block that draws a viz, but this makes it difficult to generalize the css for one viz for others, since you end up having to go hunt for another CSS cell for a separate part of the presentation. If I commit to making my CSS cell only at the top of the document, I would have to scroll all the way up to the top of the notebook to make a small tweak, then scroll all the way back down to my code block to continue work. 

Pinned cells in a side pane would solve these types of issues gracefully while maintaining the cell-style notebook workflow.

The work looks like this:

- [x] migrate to side panes that do not overlay cells (#520)
- [ ] fix header element in a side pane to not scroll with the rest of the side pane content, so the close button / title is always visible (#521)
- [x] move the close button (x) on the side pane to the right instead of left, to prevent accidental side pane closure when clicking on the main cell view (#522)
- [ ] change the state prototypes for cells to include a "pinned" key-value pair (maybe this is a pin id so we can preserve the pin order - @bcolloran we can either do this or just a boolean, any thoughts here? If we don't preserve pin order, we can preserve actual cell order) (#525)
- [ ] create a new action to pin a cell using the cell state addition above (#526)
- [ ] create a new side pane called PinnedCellsSidepane (#527)
- [ ] display the cells w/ the a restricted set of actions - (#527)
   - execute cell
   - unpin cell
   - change cell type
- [ ] add a button per cell that allows a user to unpin a cell in the side pane (#527)
- [ ] add a menu item for 'pin cell' (#528)
- [ ] add a keybinding for pinning a cell using the `UserTask` class (`meta+option+p` may be a useful one, but perhaps @wlach can guide us on this so as not to clash with editors) (#528)
- [ ] __BONUS__ include a way to scroll to the pinned cell in the main cell content (outside of the pane)

**Comment by djbarnwal** [comment]
Hi @hamilton, I would like to work on this issue.

**Comment by hamilton** [comment]
Hey @djbarnwal - that'd be great. It might be good to tackle the issues in order w/ a PR, but I'll leave it to you to appropriately break up the work so PRs are reviewable.

Feel free to ping me or @bcolloran if you have any questions while working on it.

**Comment by bcolloran** [comment]
@hamilton -- i think we should eliminate all of these issues around pin tabs in favor of #593 and the other ideas we discussed about moving in that direction. Does that work for you?

**Comment by hamilton** [comment]
After thining about it, I don't completely agree that this is mutually exclusive with #593 quite yet, and I can see this feature being useful in an `iframe` world as well, so I'd say let's hold off on closing this meta issue for now.

**Comment by bcolloran** [comment]
let me add a bit about my thinking here: because our resources are so limited, i don't think this is worth working on in the short term as a band aid on the main the workflow issues that #593 will address, and if we do end up wanting something like a pinned tab, the use cases, architecture, UI, etc will be so different that we should probably start a new issue anyway (and start a fresh round of thinking). so i still think we should close this one down, and start fresh if we need to

**Comment by hamilton** [comment]
Sounds good - feel free to close if you think conversation should move to a
fresher thread.

**Comment by bcolloran** [comment]
deprecated while we consider #593
