### ISSUE TITLE
[META] matrix / array rep design issues

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#623]
Matrices & arrays have some usability issues that are difficult to overcome for casual usage. We can make them better!

[This notebook](https://iodide-project.github.io/master/?gist=hamilton/7b7f1f87778d9180ef53a2e60d9b9bb5) demonstrates some of the problems.

- [x] very long strings cause overflow issues.
- [x] an array of very long strings causes overflow issues.
- [x] a matrix that contains a lot of very long strings causes overflow issues.
- [x] any very long array doesn't appear to get truncated at all, so if I have a thousand-row array of something like `undefined`s (which occasionally and embarrassingly happens!) my page gets a LOT longer
- [x] some types of long arrays (such as the `undefined` example) should probably not have new lines per item. Maybe none of them should, or only really long ones.

Some of these issues are common when importing data (especially the long string ones), and others are things I've noticed from general usage that have been annoyances / pains / show-stoppers in some cases (especially the long strings ones).

I'm not sure how to solve the long string issue generally, other than something that kind of truncates the string and makes it clear that there is more to see in some way. Maybe the solution is a rep that says `String [see more]` or something like that when the string is in some containing object, but that doesn't solve the One Long String problem.

For the variants of the One Long String problem, perhaps the easiest solution is simply to just set the overflow-x to scroll and just call it a day. This is essentially what devtools does for arrays of very long strings.

**Comment by bcolloran** [comment]
:100: this can be quite annoying. maybe we should revisit the devtools reps, or at least their small/medium/large approach, which would might address a lot of this?

**Comment by hamilton** [comment]
All of these design issues were fixed with #635. Closing.
