### ISSUE TITLE
META: reps (output handler) issues

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#781]
This issue to track output handler changes, particularly the move to use `react-inspector` in more places.

I've created a test notebook that tries to cover all of the basics of rep handling.

Here is the current behavior:

![image](https://user-images.githubusercontent.com/38294/44553000-1e964700-a6fa-11e8-9721-b10837023e8b.png)

![image](https://user-images.githubusercontent.com/38294/44553028-38378e80-a6fa-11e8-8197-1acf40b26728.png)

![image](https://user-images.githubusercontent.com/38294/44553046-47b6d780-a6fa-11e8-8af0-e780060bae35.png)

![image](https://user-images.githubusercontent.com/38294/44553058-53a29980-a6fa-11e8-9f82-fa1842616db3.png)

![image](https://user-images.githubusercontent.com/38294/44553130-8b114600-a6fa-11e8-892c-8ca10cd53b5e.png)

![image](https://user-images.githubusercontent.com/38294/44553144-95334480-a6fa-11e8-82c2-509f62727f30.png)

Here's the result of moving almost everything (except custom renderers) to react-inspector:

![image](https://user-images.githubusercontent.com/38294/44553230-cf044b00-a6fa-11e8-9c41-c16d51e14500.png)

![image](https://user-images.githubusercontent.com/38294/44553243-d9bee000-a6fa-11e8-83eb-872a27d8f0fe.png)

![image](https://user-images.githubusercontent.com/38294/44553260-e93e2900-a6fa-11e8-914f-03b63c2c3af1.png)

![image](https://user-images.githubusercontent.com/38294/44553283-f65b1800-a6fa-11e8-839c-eb715e731f0c.png)

![image](https://user-images.githubusercontent.com/38294/44553296-007d1680-a6fb-11e8-913d-2e9f35c1e06c.png)

**Comment by mdboom** [comment]
(Sorry about the screenshots and different scales -- Firefox screenshots doesn't seem to work with iframes).

Some observations:

- [ ] For the basic Javascript types, `react-inspector` works pretty well.  It takes up less vertical space, and is more self-consistent.  This is an easy win and will remove tons of our own code :)
- [ ] In the current version, there is code to not display an entire string when it is too long.  That seems to be broken.
- [ ] `react-inspector` doesn't seem to be doing any truncation or folding of long arrays or strings, either
- [ ] For multi-dimensional arrays and tables, our existing reps are much better than `react-inspector`
- [ ] `react-inspector` doesn't seem to know about Error or Promise as anything special.  I think we should make what we currently have blend better style-wise with `react-inspector` and use those.
- [ ] `react-inspector` won't handle nested custom reps the way our existing array and table reps do.  Those just happen to be the two reps we're most likely to keep from status quo anyway, so probably not a big deal.  If it's straightforward, it would be great to add support for custom reps to `react-inspector`'s Object rep, though.

**Comment by bcolloran** [comment]
hmm the long string code works as expected for me:

![image](https://user-images.githubusercontent.com/2380975/44608999-ce2af200-a7aa-11e8-9cb9-00ebaeff50e6.png)

**Comment by bcolloran** [comment]
closed via #1419
